# Site settings
title: Dave on DevOps
header-img: img/home-bg.jpg
email: dadiehl@gmail.com
copyright_name: Dave Diehl
description: "Testing the Jekyll engine"
baseurl: ""
url: "http://agiledavediehl.com"
twitter_username: agiledavediehl
github_username:  davediehl
email_username:  dadiehl@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
